// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditLogHead = `-- name: GetAuditLogHead :one
SELECT hash, created_at, id FROM audit_log ORDER BY created_at DESC, id DESC LIMIT 1
`

type GetAuditLogHeadRow struct {
	Hash      []byte    `json:"hash"`
	CreatedAt time.Time `json:"created_at"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetAuditLogHead(ctx context.Context) (GetAuditLogHeadRow, error) {
	row := q.db.QueryRow(ctx, getAuditLogHead)
	var i GetAuditLogHeadRow
	err := row.Scan(&i.Hash, &i.CreatedAt, &i.ID)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (id, user_id, community_id, action, entity, entity_id, before, after, ip, request_id, prev_hash, hash, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, community_id, action, entity, entity_id, before, after, ip, request_id, prev_hash, hash, created_at
`

type InsertAuditLogParams struct {
	ID          uuid.UUID   `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	CommunityID pgtype.UUID `json:"community_id"`
	Action      string      `json:"action"`
	Entity      string      `json:"entity"`
	EntityID    pgtype.UUID `json:"entity_id"`
	Before      []byte      `json:"before"`
	After       []byte      `json:"after"`
	Ip          *netip.Addr `json:"ip"`
	RequestID   pgtype.UUID `json:"request_id"`
	PrevHash    []byte      `json:"prev_hash"`
	Hash        []byte      `json:"hash"`
	CreatedAt   time.Time   `json:"created_at"`
}

// InsertAuditLog is the audit_log hash chain's single writer (D-O): the
// Semgrep rule single-writer-audit-log.yml (api/.semgrep/) fails the
// build if any generated call site other than
// internal/domain/audit.Append invokes it. Do not call this query
// directly from anywhere else.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ID,
		arg.UserID,
		arg.CommunityID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.Ip,
		arg.RequestID,
		arg.PrevHash,
		arg.Hash,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CommunityID,
		&i.Action,
		&i.Entity,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.Ip,
		&i.RequestID,
		&i.PrevHash,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogRange = `-- name: ListAuditLogRange :many
SELECT id, user_id, community_id, action, entity, entity_id, before, after, ip, request_id, prev_hash, hash, created_at FROM audit_log WHERE created_at >= $1 AND created_at <= $2 ORDER BY created_at ASC, id ASC
`

type ListAuditLogRangeParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) ListAuditLogRange(ctx context.Context, arg ListAuditLogRangeParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogRange, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CommunityID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.RequestID,
			&i.PrevHash,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
