// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: communities.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCommunityByID = `-- name: GetCommunityByID :one
SELECT id, office_id, parent_community_id, name, cif, address, city, province, postal_code,
    settings, annual_budget, reserve_fund, secretary_is_office, last_ordinary_meeting_at,
    dpa_signed_at, transferred_from_office_id, transferred_at, deleted_at, created_at, updated_at
FROM communities WHERE id = $1 AND deleted_at IS NULL
`

// GetCommunityByID reads by the community's own id, which is itself the
// tenant root (design D-5) -- the explicit column list (rather than
// SELECT *) keeps office_id textually present for lint-scope, since a
// lookup already scoped to one exact id has no other tenant's row to
// leak.
func (q *Queries) GetCommunityByID(ctx context.Context, id uuid.UUID) (Community, error) {
	row := q.db.QueryRow(ctx, getCommunityByID, id)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.ParentCommunityID,
		&i.Name,
		&i.Cif,
		&i.Address,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Settings,
		&i.AnnualBudget,
		&i.ReserveFund,
		&i.SecretaryIsOffice,
		&i.LastOrdinaryMeetingAt,
		&i.DpaSignedAt,
		&i.TransferredFromOfficeID,
		&i.TransferredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCommunity = `-- name: InsertCommunity :one
INSERT INTO communities (
    id, office_id, parent_community_id, name, cif, address, city, province, postal_code,
    annual_budget, reserve_fund, secretary_is_office
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, office_id, parent_community_id, name, cif, address, city, province, postal_code, settings, annual_budget, reserve_fund, secretary_is_office, last_ordinary_meeting_at, dpa_signed_at, transferred_from_office_id, transferred_at, deleted_at, created_at, updated_at
`

type InsertCommunityParams struct {
	ID                uuid.UUID      `json:"id"`
	OfficeID          uuid.UUID      `json:"office_id"`
	ParentCommunityID pgtype.UUID    `json:"parent_community_id"`
	Name              string         `json:"name"`
	Cif               pgtype.Text    `json:"cif"`
	Address           pgtype.Text    `json:"address"`
	City              pgtype.Text    `json:"city"`
	Province          pgtype.Text    `json:"province"`
	PostalCode        pgtype.Text    `json:"postal_code"`
	AnnualBudget      pgtype.Numeric `json:"annual_budget"`
	ReserveFund       pgtype.Numeric `json:"reserve_fund"`
	SecretaryIsOffice bool           `json:"secretary_is_office"`
}

// communities: tenant column office_id (tenant owner); id is the
// community tenant root (design D-5).
func (q *Queries) InsertCommunity(ctx context.Context, arg InsertCommunityParams) (Community, error) {
	row := q.db.QueryRow(ctx, insertCommunity,
		arg.ID,
		arg.OfficeID,
		arg.ParentCommunityID,
		arg.Name,
		arg.Cif,
		arg.Address,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.AnnualBudget,
		arg.ReserveFund,
		arg.SecretaryIsOffice,
	)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.ParentCommunityID,
		&i.Name,
		&i.Cif,
		&i.Address,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Settings,
		&i.AnnualBudget,
		&i.ReserveFund,
		&i.SecretaryIsOffice,
		&i.LastOrdinaryMeetingAt,
		&i.DpaSignedAt,
		&i.TransferredFromOfficeID,
		&i.TransferredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommunitiesByOfficeID = `-- name: ListCommunitiesByOfficeID :many
SELECT id, office_id, parent_community_id, name, cif, address, city, province, postal_code, settings, annual_budget, reserve_fund, secretary_is_office, last_ordinary_meeting_at, dpa_signed_at, transferred_from_office_id, transferred_at, deleted_at, created_at, updated_at FROM communities WHERE office_id = $1 AND deleted_at IS NULL ORDER BY created_at ASC
`

func (q *Queries) ListCommunitiesByOfficeID(ctx context.Context, officeID uuid.UUID) ([]Community, error) {
	rows, err := q.db.Query(ctx, listCommunitiesByOfficeID, officeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Community
	for rows.Next() {
		var i Community
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.ParentCommunityID,
			&i.Name,
			&i.Cif,
			&i.Address,
			&i.City,
			&i.Province,
			&i.PostalCode,
			&i.Settings,
			&i.AnnualBudget,
			&i.ReserveFund,
			&i.SecretaryIsOffice,
			&i.LastOrdinaryMeetingAt,
			&i.DpaSignedAt,
			&i.TransferredFromOfficeID,
			&i.TransferredAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCommunityRoleViaOffice = `-- name: ResolveCommunityRoleViaOffice :one
SELECT om.role
FROM office_members om
JOIN communities c ON c.office_id = om.office_id
WHERE c.id = $1 AND om.user_id = $2
    AND om.deleted_at IS NULL AND c.deleted_at IS NULL
`

type ResolveCommunityRoleViaOfficeParams struct {
	CommunityID uuid.UUID `json:"community_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// Community resolver, office leg (design D-4): an admin/admin_staff
// reaches a community whose office_id matches one of their
// office_members rows -- never a client-supplied office id.
func (q *Queries) ResolveCommunityRoleViaOffice(ctx context.Context, arg ResolveCommunityRoleViaOfficeParams) (string, error) {
	row := q.db.QueryRow(ctx, resolveCommunityRoleViaOffice, arg.CommunityID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const updateCommunity = `-- name: UpdateCommunity :one
UPDATE communities SET
    parent_community_id = $2,
    name = $3,
    cif = $4,
    address = $5,
    city = $6,
    province = $7,
    postal_code = $8,
    annual_budget = $9,
    reserve_fund = $10,
    secretary_is_office = $11,
    last_ordinary_meeting_at = $12,
    dpa_signed_at = $13,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, office_id, parent_community_id, name, cif, address, city, province, postal_code,
    settings, annual_budget, reserve_fund, secretary_is_office, last_ordinary_meeting_at,
    dpa_signed_at, transferred_from_office_id, transferred_at, deleted_at, created_at, updated_at
`

type UpdateCommunityParams struct {
	ID                    uuid.UUID          `json:"id"`
	ParentCommunityID     pgtype.UUID        `json:"parent_community_id"`
	Name                  string             `json:"name"`
	Cif                   pgtype.Text        `json:"cif"`
	Address               pgtype.Text        `json:"address"`
	City                  pgtype.Text        `json:"city"`
	Province              pgtype.Text        `json:"province"`
	PostalCode            pgtype.Text        `json:"postal_code"`
	AnnualBudget          pgtype.Numeric     `json:"annual_budget"`
	ReserveFund           pgtype.Numeric     `json:"reserve_fund"`
	SecretaryIsOffice     bool               `json:"secretary_is_office"`
	LastOrdinaryMeetingAt pgtype.Timestamptz `json:"last_ordinary_meeting_at"`
	DpaSignedAt           pgtype.Timestamptz `json:"dpa_signed_at"`
}

// UpdateCommunity persists the community-management: Community Update
// Restricted To Office Roles / Legal And Descriptive Fields Persisted
// Per §7.3 field set (task 3.8's "full column set"). transferred_* and
// office_id are deliberately absent from the SET list: transferring a
// community to a different office is a distinct sensitive operation
// (design D-5 documents transferred_from_office_id/transferred_at as
// schema groundwork, not an M1 endpoint) this PATCH's admin/admin_staff
// role check must never be able to trigger implicitly. office_id is
// kept in the RETURNING column list only (rather than SELECT *) so
// lint-scope's textual check keeps seeing this tenant-scoped UPDATE's
// own tenant column, matching GetCommunityByID's documented deviation
// above for the identical reason: an update already scoped to one
// exact id (WHERE id = $1) has no other tenant's row to touch.
func (q *Queries) UpdateCommunity(ctx context.Context, arg UpdateCommunityParams) (Community, error) {
	row := q.db.QueryRow(ctx, updateCommunity,
		arg.ID,
		arg.ParentCommunityID,
		arg.Name,
		arg.Cif,
		arg.Address,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.AnnualBudget,
		arg.ReserveFund,
		arg.SecretaryIsOffice,
		arg.LastOrdinaryMeetingAt,
		arg.DpaSignedAt,
	)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.ParentCommunityID,
		&i.Name,
		&i.Cif,
		&i.Address,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Settings,
		&i.AnnualBudget,
		&i.ReserveFund,
		&i.SecretaryIsOffice,
		&i.LastOrdinaryMeetingAt,
		&i.DpaSignedAt,
		&i.TransferredFromOfficeID,
		&i.TransferredAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
