// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVisibleIncidentByID = `-- name: GetVisibleIncidentByID :one
SELECT i.id, i.community_id, i.unit_id, i.created_by, i.title, i.description, i.category, i.priority, i.status, i.scope, i.location_text, i.affected_count, i.deleted_at, i.created_at, i.updated_at
FROM incidents i
JOIN communities c ON c.id = i.community_id AND c.deleted_at IS NULL
WHERE i.id = $1
    AND i.community_id = $2
    AND i.deleted_at IS NULL
    AND (
        EXISTS (
            SELECT 1 FROM office_members om
            WHERE om.office_id = c.office_id
                AND om.user_id = $3
                AND om.role IN ('admin', 'admin_staff')
                AND om.deleted_at IS NULL
        )
        OR (
            i.scope = 'common'
            AND EXISTS (
                SELECT 1
                FROM unit_members um
                JOIN units u ON u.id = um.unit_id
                    AND u.community_id = um.community_id
                    AND u.deleted_at IS NULL
                WHERE um.community_id = i.community_id
                    AND um.user_id = $3
                    AND um.deleted_at IS NULL
                    AND (um.valid_from IS NULL OR um.valid_from <= now())
                    AND (um.valid_to IS NULL OR um.valid_to > now())
            )
        )
        OR (
            i.scope = 'unit'
            AND (
                i.created_by = $3
                OR EXISTS (
                    SELECT 1
                    FROM unit_members um
                    JOIN units u ON u.id = um.unit_id
                        AND u.community_id = um.community_id
                        AND u.deleted_at IS NULL
                    WHERE um.community_id = i.community_id
                        AND um.unit_id = i.unit_id
                        AND um.user_id = $3
                        AND um.deleted_at IS NULL
                        AND (um.valid_from IS NULL OR um.valid_from <= now())
                        AND (um.valid_to IS NULL OR um.valid_to > now())
                )
            )
        )
    )
`

type GetVisibleIncidentByIDParams struct {
	ID          uuid.UUID `json:"id"`
	CommunityID uuid.UUID `json:"community_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// Detail lookup repeats the complete visibility predicate and binds both
// community and caller, so foreign/private ids resolve as no row.
func (q *Queries) GetVisibleIncidentByID(ctx context.Context, arg GetVisibleIncidentByIDParams) (Incident, error) {
	row := q.db.QueryRow(ctx, getVisibleIncidentByID, arg.ID, arg.CommunityID, arg.UserID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.UnitID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.Scope,
		&i.LocationText,
		&i.AffectedCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIncident = `-- name: InsertIncident :one
INSERT INTO incidents (
    id, community_id, unit_id, created_by, title, description, category, scope, location_text
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, community_id, unit_id, created_by, title, description, category, priority, status, scope, location_text, affected_count, deleted_at, created_at, updated_at
`

type InsertIncidentParams struct {
	ID           uuid.UUID   `json:"id"`
	CommunityID  uuid.UUID   `json:"community_id"`
	UnitID       pgtype.UUID `json:"unit_id"`
	CreatedBy    uuid.UUID   `json:"created_by"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	Category     string      `json:"category"`
	Scope        string      `json:"scope"`
	LocationText pgtype.Text `json:"location_text"`
}

// incidents: tenant column community_id (design D-5).
func (q *Queries) InsertIncident(ctx context.Context, arg InsertIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, insertIncident,
		arg.ID,
		arg.CommunityID,
		arg.UnitID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Scope,
		arg.LocationText,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.UnitID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.Scope,
		&i.LocationText,
		&i.AffectedCount,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVisibleIncidents = `-- name: ListVisibleIncidents :many
SELECT i.id, i.community_id, i.unit_id, i.created_by, i.title, i.description, i.category, i.priority, i.status, i.scope, i.location_text, i.affected_count, i.deleted_at, i.created_at, i.updated_at
FROM incidents i
JOIN communities c ON c.id = i.community_id AND c.deleted_at IS NULL
WHERE i.community_id = $1
    AND i.deleted_at IS NULL
    AND (
        EXISTS (
            SELECT 1 FROM office_members om
            WHERE om.office_id = c.office_id
                AND om.user_id = $2
                AND om.role IN ('admin', 'admin_staff')
                AND om.deleted_at IS NULL
        )
        OR (
            i.scope = 'common'
            AND EXISTS (
                SELECT 1
                FROM unit_members um
                JOIN units u ON u.id = um.unit_id
                    AND u.community_id = um.community_id
                    AND u.deleted_at IS NULL
                WHERE um.community_id = i.community_id
                    AND um.user_id = $2
                    AND um.deleted_at IS NULL
                    AND (um.valid_from IS NULL OR um.valid_from <= now())
                    AND (um.valid_to IS NULL OR um.valid_to > now())
            )
        )
        OR (
            i.scope = 'unit'
            AND (
                i.created_by = $2
                OR EXISTS (
                    SELECT 1
                    FROM unit_members um
                    JOIN units u ON u.id = um.unit_id
                        AND u.community_id = um.community_id
                        AND u.deleted_at IS NULL
                    WHERE um.community_id = i.community_id
                        AND um.unit_id = i.unit_id
                        AND um.user_id = $2
                        AND um.deleted_at IS NULL
                        AND (um.valid_from IS NULL OR um.valid_from <= now())
                        AND (um.valid_to IS NULL OR um.valid_to > now())
                )
            )
        )
    )
    AND ($3::text IS NULL OR i.status = $3::text)
    AND ($4::text IS NULL OR i.category = $4::text)
    AND ($5::uuid IS NULL OR i.unit_id = $5::uuid)
    AND (
        $6::timestamptz IS NULL
        OR (i.created_at, i.id) < (
            $6::timestamptz,
            $7::uuid
        )
    )
ORDER BY i.created_at DESC, i.id DESC
LIMIT $8::int
`

type ListVisibleIncidentsParams struct {
	CommunityID     uuid.UUID          `json:"community_id"`
	UserID          uuid.UUID          `json:"user_id"`
	Status          pgtype.Text        `json:"status"`
	Category        pgtype.Text        `json:"category"`
	UnitID          pgtype.UUID        `json:"unit_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

// A private unit incident is visible only to its creator, an active
// member of that exact unit, or an admin/admin_staff of the community's
// owning office. Board roles are intentionally not an authorization
// predicate: being president alone does not grant private-unit access.
// Common incidents require community membership unless the caller is a
// scoped office administrator. Caller and community ids are explicit
// bound inputs, never inferred from an incident id alone.
func (q *Queries) ListVisibleIncidents(ctx context.Context, arg ListVisibleIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listVisibleIncidents,
		arg.CommunityID,
		arg.UserID,
		arg.Status,
		arg.Category,
		arg.UnitID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.UnitID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Priority,
			&i.Status,
			&i.Scope,
			&i.LocationText,
			&i.AffectedCount,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
