// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, community_id, unit_id, email, role, token_hash, short_code_hash, status, expires_at, accepted_at, sent_count, failed_attempts, created_at, updated_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.UnitID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ShortCodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.SentCount,
		&i.FailedAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationCommunityID = `-- name: GetInvitationCommunityID :one
SELECT community_id FROM invitations WHERE id = $1
`

// Invitation resolver (design D-4): an {invitationId} route resolves
// community membership via the invitation's own owning community_id.
func (q *Queries) GetInvitationCommunityID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getInvitationCommunityID, id)
	var community_id uuid.UUID
	err := row.Scan(&community_id)
	return community_id, err
}

const insertInvitation = `-- name: InsertInvitation :one
INSERT INTO invitations (id, community_id, unit_id, email, role, token_hash, short_code_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, community_id, unit_id, email, role, token_hash, short_code_hash, status, expires_at, accepted_at, sent_count, failed_attempts, created_at, updated_at
`

type InsertInvitationParams struct {
	ID            uuid.UUID   `json:"id"`
	CommunityID   uuid.UUID   `json:"community_id"`
	UnitID        pgtype.UUID `json:"unit_id"`
	Email         pgtype.Text `json:"email"`
	Role          string      `json:"role"`
	TokenHash     []byte      `json:"token_hash"`
	ShortCodeHash []byte      `json:"short_code_hash"`
	ExpiresAt     time.Time   `json:"expires_at"`
}

// invitations: tenant column community_id (design D-5).
func (q *Queries) InsertInvitation(ctx context.Context, arg InsertInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, insertInvitation,
		arg.ID,
		arg.CommunityID,
		arg.UnitID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ShortCodeHash,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.UnitID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ShortCodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.SentCount,
		&i.FailedAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvitationsByCommunityID = `-- name: ListInvitationsByCommunityID :many
SELECT id, community_id, unit_id, email, role, token_hash, short_code_hash, status, expires_at, accepted_at, sent_count, failed_attempts, created_at, updated_at FROM invitations WHERE community_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByCommunityID(ctx context.Context, communityID uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByCommunityID, communityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.UnitID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.ShortCodeHash,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.SentCount,
			&i.FailedAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
