// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          uuid.UUID   `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	CommunityID pgtype.UUID `json:"community_id"`
	Action      string      `json:"action"`
	Entity      string      `json:"entity"`
	EntityID    pgtype.UUID `json:"entity_id"`
	Before      []byte      `json:"before"`
	After       []byte      `json:"after"`
	Ip          *netip.Addr `json:"ip"`
	RequestID   pgtype.UUID `json:"request_id"`
	PrevHash    []byte      `json:"prev_hash"`
	Hash        []byte      `json:"hash"`
	CreatedAt   time.Time   `json:"created_at"`
}

type OtpChallenge struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Purpose    string             `json:"purpose"`
	CodeHash   []byte             `json:"code_hash"`
	Channel    string             `json:"channel"`
	ExpiresAt  time.Time          `json:"expires_at"`
	Attempts   int32              `json:"attempts"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type PasswordResetToken struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	TokenHash   []byte             `json:"token_hash"`
	ExpiresAt   time.Time          `json:"expires_at"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	RequestedIp *netip.Addr        `json:"requested_ip"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	FamilyID         uuid.UUID          `json:"family_id"`
	DeviceName       pgtype.Text        `json:"device_name"`
	Platform         string             `json:"platform"`
	Ip               *netip.Addr        `json:"ip"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	Name                string             `json:"name"`
	Phone               pgtype.Text        `json:"phone"`
	PhoneVerifiedAt     pgtype.Timestamptz `json:"phone_verified_at"`
	Locale              string             `json:"locale"`
	AvatarKey           pgtype.Text        `json:"avatar_key"`
	IDDocumentEncrypted []byte             `json:"id_document_encrypted"`
	NotificationPrefs   json.RawMessage    `json:"notification_prefs"`
	IsSuperadmin        bool               `json:"is_superadmin"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type UserMfa struct {
	UserID              uuid.UUID          `json:"user_id"`
	TotpSecretEncrypted []byte             `json:"totp_secret_encrypted"`
	EnabledAt           pgtype.Timestamptz `json:"enabled_at"`
	LastTotpStep        pgtype.Int8        `json:"last_totp_step"`
	RecoveryCodesHashed []string           `json:"recovery_codes_hashed"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}
