// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offices.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOfficeByID = `-- name: GetOfficeByID :one
SELECT id, name, cif, email, phone, address, logo_key, collegiate_number, deleted_at, created_at, updated_at FROM offices WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOfficeByID(ctx context.Context, id uuid.UUID) (Office, error) {
	row := q.db.QueryRow(ctx, getOfficeByID, id)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cif,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.LogoKey,
		&i.CollegiateNumber,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOffice = `-- name: InsertOffice :one
INSERT INTO offices (id, name, cif, email, phone, address, logo_key, collegiate_number)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, cif, email, phone, address, logo_key, collegiate_number, deleted_at, created_at, updated_at
`

type InsertOfficeParams struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	Cif              string      `json:"cif"`
	Email            pgtype.Text `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	Address          pgtype.Text `json:"address"`
	LogoKey          pgtype.Text `json:"logo_key"`
	CollegiateNumber pgtype.Text `json:"collegiate_number"`
}

// offices: id is itself the tenant root (design D-5).
func (q *Queries) InsertOffice(ctx context.Context, arg InsertOfficeParams) (Office, error) {
	row := q.db.QueryRow(ctx, insertOffice,
		arg.ID,
		arg.Name,
		arg.Cif,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.LogoKey,
		arg.CollegiateNumber,
	)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cif,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.LogoKey,
		&i.CollegiateNumber,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
