// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: office_members.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getOfficeMemberByOfficeAndUser = `-- name: GetOfficeMemberByOfficeAndUser :one
SELECT id, office_id, user_id, role, deleted_at, created_at, updated_at FROM office_members WHERE office_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetOfficeMemberByOfficeAndUserParams struct {
	OfficeID uuid.UUID `json:"office_id"`
	UserID   uuid.UUID `json:"user_id"`
}

// office resolver (design D-4): office scope resolves by (office_id,
// user_id), never from a header or body.
func (q *Queries) GetOfficeMemberByOfficeAndUser(ctx context.Context, arg GetOfficeMemberByOfficeAndUserParams) (OfficeMember, error) {
	row := q.db.QueryRow(ctx, getOfficeMemberByOfficeAndUser, arg.OfficeID, arg.UserID)
	var i OfficeMember
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.UserID,
		&i.Role,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOfficeMember = `-- name: InsertOfficeMember :one
INSERT INTO office_members (id, office_id, user_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, office_id, user_id, role, deleted_at, created_at, updated_at
`

type InsertOfficeMemberParams struct {
	ID       uuid.UUID `json:"id"`
	OfficeID uuid.UUID `json:"office_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
}

// office_members: tenant column office_id (design D-5).
func (q *Queries) InsertOfficeMember(ctx context.Context, arg InsertOfficeMemberParams) (OfficeMember, error) {
	row := q.db.QueryRow(ctx, insertOfficeMember,
		arg.ID,
		arg.OfficeID,
		arg.UserID,
		arg.Role,
	)
	var i OfficeMember
	err := row.Scan(
		&i.ID,
		&i.OfficeID,
		&i.UserID,
		&i.Role,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOfficeMembers = `-- name: ListOfficeMembers :many
SELECT id, office_id, user_id, role, deleted_at, created_at, updated_at FROM office_members WHERE office_id = $1 AND deleted_at IS NULL ORDER BY created_at ASC
`

func (q *Queries) ListOfficeMembers(ctx context.Context, officeID uuid.UUID) ([]OfficeMember, error) {
	rows, err := q.db.Query(ctx, listOfficeMembers, officeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfficeMember
	for rows.Next() {
		var i OfficeMember
		if err := rows.Scan(
			&i.ID,
			&i.OfficeID,
			&i.UserID,
			&i.Role,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficeMembershipsByUserID = `-- name: ListOfficeMembershipsByUserID :many
SELECT office_id, role FROM office_members WHERE user_id = $1 AND deleted_at IS NULL
`

type ListOfficeMembershipsByUserIDRow struct {
	OfficeID uuid.UUID `json:"office_id"`
	Role     string    `json:"role"`
}

// Self resolver (design D-4): the caller's full office-membership set,
// for GET /v1/me. Looked up by user, not by office -- the documented
// exception D-5 names for office_members_user_id_idx.
func (q *Queries) ListOfficeMembershipsByUserID(ctx context.Context, userID uuid.UUID) ([]ListOfficeMembershipsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listOfficeMembershipsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOfficeMembershipsByUserIDRow
	for rows.Next() {
		var i ListOfficeMembershipsByUserIDRow
		if err := rows.Scan(&i.OfficeID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
