// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp_challenges.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getOTPChallenge = `-- name: GetOTPChallenge :one
SELECT id, user_id, purpose, code_hash, channel, expires_at, attempts, verified_at, created_at, updated_at FROM otp_challenges WHERE id = $1
`

func (q *Queries) GetOTPChallenge(ctx context.Context, id uuid.UUID) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, getOTPChallenge, id)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.Channel,
		&i.ExpiresAt,
		&i.Attempts,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementOTPChallengeAttempts = `-- name: IncrementOTPChallengeAttempts :one
UPDATE otp_challenges SET attempts = attempts + 1, updated_at = now()
WHERE id = $1
RETURNING attempts
`

func (q *Queries) IncrementOTPChallengeAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementOTPChallengeAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const insertOTPChallenge = `-- name: InsertOTPChallenge :one
INSERT INTO otp_challenges (id, user_id, purpose, code_hash, channel, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, purpose, code_hash, channel, expires_at, attempts, verified_at, created_at, updated_at
`

type InsertOTPChallengeParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Purpose   string    `json:"purpose"`
	CodeHash  []byte    `json:"code_hash"`
	Channel   string    `json:"channel"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertOTPChallenge(ctx context.Context, arg InsertOTPChallengeParams) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, insertOTPChallenge,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.CodeHash,
		arg.Channel,
		arg.ExpiresAt,
	)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.Channel,
		&i.ExpiresAt,
		&i.Attempts,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOTPChallengeVerified = `-- name: MarkOTPChallengeVerified :exec
UPDATE otp_challenges SET verified_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkOTPChallengeVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPChallengeVerified, id)
	return err
}
