// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :exec
UPDATE password_reset_tokens SET used_at = now(), updated_at = now()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumePasswordResetToken, id)
	return err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, requested_ip, created_at, updated_at FROM password_reset_tokens WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash []byte) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RequestedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPasswordResetToken = `-- name: InsertPasswordResetToken :one
INSERT INTO password_reset_tokens (id, user_id, token_hash, expires_at, requested_ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, expires_at, used_at, requested_ip, created_at, updated_at
`

type InsertPasswordResetTokenParams struct {
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	TokenHash   []byte      `json:"token_hash"`
	ExpiresAt   time.Time   `json:"expires_at"`
	RequestedIp *netip.Addr `json:"requested_ip"`
}

func (q *Queries) InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, insertPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.RequestedIp,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RequestedIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
