// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// AcceptInvitation implements design D-6's single-use write: the status
	// transition only succeeds when the invitation is still pending and
	// unexpired, so a concurrent or repeated accept observes zero rows
	// rather than racing a prior read.
	AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (uuid.UUID, error)
	ConfirmUserMFAEnrollment(ctx context.Context, userID uuid.UUID) error
	ConsumePasswordResetToken(ctx context.Context, id uuid.UUID) error
	ConsumeUserMFARecoveryCode(ctx context.Context, arg ConsumeUserMFARecoveryCodeParams) (int64, error)
	// CountOfficeMembersByOfficeID backs community-management: Community
	// Detail Excludes Cross-Milestone Aggregates -- the community detail
	// response's office-member count is a plain count of the owning
	// office's own rows, never a reserve-fund/quorum/balance aggregate.
	CountOfficeMembersByOfficeID(ctx context.Context, officeID uuid.UUID) (int64, error)
	// CountUnitsByCommunityID backs community-management: Community Detail
	// Excludes Cross-Milestone Aggregates -- the community detail response's
	// unit count is a plain count of this tenant's own rows, never a
	// reserve-fund/quorum/balance aggregate from a later milestone.
	CountUnitsByCommunityID(ctx context.Context, communityID uuid.UUID) (int64, error)
	DeleteUnitMember(ctx context.Context, arg DeleteUnitMemberParams) (int64, error)
	// platform-bootstrap: Idempotent Superadmin Bootstrap -- a second
	// bootstrap-superadmin run against an existing, non-superadmin user
	// (e.g. one first created by seed) promotes it, but NEVER touches its
	// password_hash.
	EnsureSuperadmin(ctx context.Context, id uuid.UUID) error
	GetAuditLogHead(ctx context.Context) (GetAuditLogHeadRow, error)
	// GetCommunityByID reads by the community's own id, which is itself the
	// tenant root (design D-5) -- the explicit column list (rather than
	// SELECT *) keeps office_id textually present for lint-scope, since a
	// lookup already scoped to one exact id has no other tenant's row to
	// leak.
	GetCommunityByID(ctx context.Context, id uuid.UUID) (Community, error)
	// GetInvitationByID is tenant-scoped by both id and community_id: the
	// caller's community membership was already resolved and role-checked
	// by scoped.Community/scoped.Invitation before this query ever runs,
	// but the explicit community_id predicate is the same defense-in-depth
	// unit_members.sql's three-bound queries already establish.
	GetInvitationByID(ctx context.Context, arg GetInvitationByIDParams) (Invitation, error)
	GetInvitationByShortCodeHash(ctx context.Context, shortCodeHash []byte) (Invitation, error)
	// GetInvitationByTokenHash and GetInvitationByShortCodeHash back the
	// unauthenticated preview/accept flow (invitations spec: "Preview
	// Endpoint Is POST"; "Accept Creates Or Links An Account"). Both are
	// global-uniqueness lookups by design (token_hash/short_code_hash are
	// each UNIQUE across every community), so neither takes a tenant
	// parameter -- the caller has no community context yet at this point in
	// the flow, which is exactly why the invitation row itself is what
	// supplies it (authz.ResolveCommunityViaInvitation, used by the
	// AUTHENTICATED resend/revoke routes, is a completely separate path).
	GetInvitationByTokenHash(ctx context.Context, tokenHash []byte) (Invitation, error)
	// Invitation resolver (design D-4): a {invitationId} route resolves
	// community membership via the invitation's own owning community_id,
	// never a caller-supplied value. Returns the community_id regardless of
	// status: a revoked/accepted/blocked invitation is still tied to a real
	// community for cross-tenant isolation purposes.
	GetInvitationCommunityID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetOTPChallenge(ctx context.Context, id uuid.UUID) (OtpChallenge, error)
	GetOfficeByID(ctx context.Context, id uuid.UUID) (Office, error)
	// office resolver (design D-4): office scope resolves by (office_id,
	// user_id), never from a header or body.
	GetOfficeMemberByOfficeAndUser(ctx context.Context, arg GetOfficeMemberByOfficeAndUserParams) (OfficeMember, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash []byte) (PasswordResetToken, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (Session, error)
	GetUnitByID(ctx context.Context, id uuid.UUID) (Unit, error)
	// Unit resolver (design D-4): a {unitId} route resolves community
	// membership via the unit's own community_id, never a caller-supplied
	// value.
	GetUnitCommunityID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// unit-management: Unit Member Management Scoped To Community --
	// unit_id AND community_id are both bound parameters (never just the
	// path-supplied memberId alone), so a memberId belonging to a
	// different unit or a different community can never be read, updated
	// or deleted through this unit's route.
	GetUnitMemberByID(ctx context.Context, arg GetUnitMemberByIDParams) (UnitMember, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserMFA(ctx context.Context, userID uuid.UUID) (UserMfa, error)
	// IncrementInvitationFailedAttempts records that a preview/accept call
	// RESOLVED to this real invitation row (design D-6: "invitations.
	// failed_attempts is still incremented, but only when the code resolved
	// to a real invitation, and it is gate evidence rather than the
	// mechanism"). It is called unconditionally on resolution, independent
	// of whether the call goes on to succeed -- the enumeration lockout
	// itself is enforced entirely by the IP+device AttemptCounter, never by
	// this column (invitations spec: "failed_attempts alone does not
	// enforce the lockout"). community_id is bound from the JUST-RESOLVED
	// row (the caller always has it in hand at this point), so this is a
	// genuine tenant filter, not merely a textual one.
	IncrementInvitationFailedAttempts(ctx context.Context, arg IncrementInvitationFailedAttemptsParams) error
	IncrementOTPChallengeAttempts(ctx context.Context, id uuid.UUID) (int32, error)
	// InsertAuditLog is the audit_log hash chain's single writer (D-O): the
	// Semgrep rule single-writer-audit-log.yml (api/.semgrep/) fails the
	// build if any generated call site other than
	// internal/domain/audit.Append invokes it. Do not call this query
	// directly from anywhere else.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	// communities: tenant column office_id (tenant owner); id is the
	// community tenant root (design D-5).
	InsertCommunity(ctx context.Context, arg InsertCommunityParams) (Community, error)
	// invitations: tenant column community_id (design D-5).
	InsertInvitation(ctx context.Context, arg InsertInvitationParams) (Invitation, error)
	InsertOTPChallenge(ctx context.Context, arg InsertOTPChallengeParams) (OtpChallenge, error)
	// offices: id is itself the tenant root (design D-5).
	InsertOffice(ctx context.Context, arg InsertOfficeParams) (Office, error)
	// office_members: tenant column office_id (design D-5).
	InsertOfficeMember(ctx context.Context, arg InsertOfficeMemberParams) (OfficeMember, error)
	InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) (PasswordResetToken, error)
	// mfa_at is set at INSERT time and never updated afterwards: how a
	// session authenticated is decided once, when it is created (login) or
	// inherited from the row it rotates from (refresh). A session cannot be
	// promoted to second-factor authenticated later without a fresh login.
	InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error)
	// units: tenant column community_id (design D-5).
	InsertUnit(ctx context.Context, arg InsertUnitParams) (Unit, error)
	// unit_members: tenant column community_id, denormalised NOT NULL FK
	// (design D-5). electronic_notifications_consent_at/consent_text_version
	// are settable at creation (unit-management: Consent And Notification
	// Fields Captured Per Member, "created without consent" scenario --
	// null when the caller passes no consent).
	InsertUnitMember(ctx context.Context, arg InsertUnitMemberParams) (UnitMember, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	// platform-bootstrap: Idempotent Superadmin Bootstrap / seed Refuses To
	// Run Outside Non-Production -- both bootstrap-superadmin and seed need
	// an idempotent insert that never duplicates and never errors on a
	// second run. Zero affected rows means the email already existed; the
	// caller is expected to load the existing row (GetUserByEmail) and, for
	// bootstrap-superadmin only, ensure is_superadmin via EnsureSuperadmin.
	InsertUserIgnoreConflict(ctx context.Context, arg InsertUserIgnoreConflictParams) (int64, error)
	// auth-mfa-totp delta: Mandatory TOTP For Admin And Admin_staff Scope
	// Access. Always returns exactly one row (true/false), never
	// pgx.ErrNoRows, so a caller who never enrolled resolves cleanly to
	// false instead of a "no rows" error the resolver would have to special
	// -case.
	IsUserMFAEnabled(ctx context.Context, userID uuid.UUID) (bool, error)
	ListAuditLogRange(ctx context.Context, arg ListAuditLogRangeParams) ([]AuditLog, error)
	ListCommunitiesByOfficeID(ctx context.Context, officeID uuid.UUID) ([]Community, error)
	ListInvitationsByCommunityID(ctx context.Context, communityID uuid.UUID) ([]Invitation, error)
	ListLiveSessionsByFamilyID(ctx context.Context, familyID uuid.UUID) ([]Session, error)
	ListOfficeMembers(ctx context.Context, officeID uuid.UUID) ([]OfficeMember, error)
	// Self resolver (design D-4): the caller's full office-membership set,
	// for GET /v1/me. Looked up by user, not by office -- the documented
	// exception D-5 names for office_members_user_id_idx.
	ListOfficeMembershipsByUserID(ctx context.Context, userID uuid.UUID) ([]ListOfficeMembershipsByUserIDRow, error)
	ListUnitMembersByCommunityID(ctx context.Context, communityID uuid.UUID) ([]UnitMember, error)
	ListUnitMembersByUnitID(ctx context.Context, arg ListUnitMembersByUnitIDParams) ([]UnitMember, error)
	// Self resolver (design D-4): the caller's full unit-membership set,
	// for GET /v1/me.
	ListUnitMembershipsByUserID(ctx context.Context, userID uuid.UUID) ([]ListUnitMembershipsByUserIDRow, error)
	ListUnitsByCommunityID(ctx context.Context, communityID uuid.UUID) ([]Unit, error)
	MarkOTPChallengeVerified(ctx context.Context, id uuid.UUID) error
	// Community resolver, office leg (design D-4): an admin/admin_staff
	// reaches a community whose office_id matches one of their
	// office_members rows -- never a client-supplied office id.
	ResolveCommunityRoleViaOffice(ctx context.Context, arg ResolveCommunityRoleViaOfficeParams) (string, error)
	// Community resolver, unit leg (design D-4): a caller's unit_members
	// row for this community_id, never derived from a header.
	ResolveCommunityRoleViaUnit(ctx context.Context, arg ResolveCommunityRoleViaUnitParams) (string, error)
	// RevokeInvitation implements DELETE /v1/invitations/:id (invitations
	// spec: "Resend And Revoke"). Only a still-pending invitation can be
	// revoked; zero rows returned means it was already accepted/revoked/
	// blocked, which the handler maps to a 409 rather than silently
	// reporting success.
	RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (uuid.UUID, error)
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RevokeSessionFamily(ctx context.Context, familyID uuid.UUID) error
	// RotateInvitationShortCode backs POST /v1/invitations/:id/resend. It
	// re-issues the short code and counts the send in ONE statement, because the
	// two must never diverge: sent_count is the operator-visible evidence that a
	// delivery happened, and it used to be incremented by a resend that dispatched
	// nothing at all (R3-resend-invitation-dispatches-nothing, review lineage
	// review-f855997b550a986d).
	//
	// Re-issuing rather than redelivering is forced by the storage model and
	// chosen deliberately: only one-way digests of the code (an HMAC) and the
	// token are persisted, so the plaintext an invitation email renders is
	// unrecoverable here. See the handler for why a recoverable copy was rejected.
	//
	// Pending-only and tenant-scoped, exactly like RevokeInvitation: zero rows
	// means the invitation is no longer pending, which the handler maps to 409
	// rather than silently reporting a send. email is returned because the job
	// payload needs it and the caller has only the invitation id in hand.
	RotateInvitationShortCode(ctx context.Context, arg RotateInvitationShortCodeParams) (RotateInvitationShortCodeRow, error)
	SetUserMFARecoveryCodes(ctx context.Context, arg SetUserMFARecoveryCodesParams) error
	// SumParticipationCoefficientByCommunityID backs unit-management:
	// Participation Coefficient Sum Is A Warning, Not A Block (§5.2) -- the
	// sum is read-only, never a write-time constraint, so the caller
	// decides what to do with a sum outside 100 ± 0.01.
	SumParticipationCoefficientByCommunityID(ctx context.Context, communityID uuid.UUID) (pgtype.Numeric, error)
	// SweepExpiredInvitations implements the daily invitations.expire job
	// (design D-6; PRD §7.4 job table; task 6.18/6.19). It transitions
	// past-expiry pending rows to 'blocked' -- the only CHECK-permitted
	// terminal value left once 'accepted' and 'revoked' are excluded, since
	// the invitations_status_check constraint (00008_invitations.sql) does
	// not include an 'expired' value: expiry is reported at READ time via
	// derivation (status='pending' AND expires_at<=now() reads as
	// "expired"), and this sweep is the bookkeeping step that makes the
	// stored column converge for reporting once the derivation window has
	// passed, matching design D-6's "expired is derived at read time and
	// never stored, and the daily invitations.expire job sweeps."
	SweepExpiredInvitations(ctx context.Context) (int64, error)
	TouchSessionLastUsed(ctx context.Context, id uuid.UUID) error
	// UpdateCommunity persists the community-management: Community Update
	// Restricted To Office Roles / Legal And Descriptive Fields Persisted
	// Per §7.3 field set (task 3.8's "full column set"). transferred_* and
	// office_id are deliberately absent from the SET list: transferring a
	// community to a different office is a distinct sensitive operation
	// (design D-5 documents transferred_from_office_id/transferred_at as
	// schema groundwork, not an M1 endpoint) this PATCH's admin/admin_staff
	// role check must never be able to trigger implicitly. office_id is
	// kept in the RETURNING column list only (rather than SELECT *) so
	// lint-scope's textual check keeps seeing this tenant-scoped UPDATE's
	// own tenant column, matching GetCommunityByID's documented deviation
	// above for the identical reason: an update already scoped to one
	// exact id (WHERE id = $1) has no other tenant's row to touch.
	UpdateCommunity(ctx context.Context, arg UpdateCommunityParams) (Community, error)
	UpdateUnitMember(ctx context.Context, arg UpdateUnitMemberParams) (UnitMember, error)
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error
	UpdateUserMFALastTOTPStep(ctx context.Context, arg UpdateUserMFALastTOTPStepParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertUserMFA(ctx context.Context, arg UpsertUserMFAParams) (UserMfa, error)
}

var _ Querier = (*Queries)(nil)
