// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConfirmUserMFAEnrollment(ctx context.Context, userID uuid.UUID) error
	ConsumePasswordResetToken(ctx context.Context, id uuid.UUID) error
	ConsumeUserMFARecoveryCode(ctx context.Context, arg ConsumeUserMFARecoveryCodeParams) (int64, error)
	// platform-bootstrap: Idempotent Superadmin Bootstrap -- a second
	// bootstrap-superadmin run against an existing, non-superadmin user
	// (e.g. one first created by seed) promotes it, but NEVER touches its
	// password_hash.
	EnsureSuperadmin(ctx context.Context, id uuid.UUID) error
	GetAuditLogHead(ctx context.Context) (GetAuditLogHeadRow, error)
	GetOTPChallenge(ctx context.Context, id uuid.UUID) (OtpChallenge, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash []byte) (PasswordResetToken, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserMFA(ctx context.Context, userID uuid.UUID) (UserMfa, error)
	IncrementOTPChallengeAttempts(ctx context.Context, id uuid.UUID) (int32, error)
	// InsertAuditLog is the audit_log hash chain's single writer (D-O): the
	// Semgrep rule single-writer-audit-log.yml (api/.semgrep/) fails the
	// build if any generated call site other than
	// internal/domain/audit.Append invokes it. Do not call this query
	// directly from anywhere else.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertOTPChallenge(ctx context.Context, arg InsertOTPChallengeParams) (OtpChallenge, error)
	InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) (PasswordResetToken, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	// platform-bootstrap: Idempotent Superadmin Bootstrap / seed Refuses To
	// Run Outside Non-Production -- both bootstrap-superadmin and seed need
	// an idempotent insert that never duplicates and never errors on a
	// second run. Zero affected rows means the email already existed; the
	// caller is expected to load the existing row (GetUserByEmail) and, for
	// bootstrap-superadmin only, ensure is_superadmin via EnsureSuperadmin.
	InsertUserIgnoreConflict(ctx context.Context, arg InsertUserIgnoreConflictParams) (int64, error)
	ListAuditLogRange(ctx context.Context, arg ListAuditLogRangeParams) ([]AuditLog, error)
	ListLiveSessionsByFamilyID(ctx context.Context, familyID uuid.UUID) ([]Session, error)
	MarkOTPChallengeVerified(ctx context.Context, id uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RevokeSessionFamily(ctx context.Context, familyID uuid.UUID) error
	SetUserMFARecoveryCodes(ctx context.Context, arg SetUserMFARecoveryCodesParams) error
	TouchSessionLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error
	UpdateUserMFALastTOTPStep(ctx context.Context, arg UpdateUserMFALastTOTPStepParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertUserMFA(ctx context.Context, arg UpsertUserMFAParams) (UserMfa, error)
}

var _ Querier = (*Queries)(nil)
