// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, refresh_token_hash, family_id, device_name, platform, ip, last_used_at, expires_at, revoked_at, created_at, updated_at FROM sessions WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.FamilyID,
		&i.DeviceName,
		&i.Platform,
		&i.Ip,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (id, user_id, refresh_token_hash, family_id, device_name, platform, ip, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, refresh_token_hash, family_id, device_name, platform, ip, last_used_at, expires_at, revoked_at, created_at, updated_at
`

type InsertSessionParams struct {
	ID               uuid.UUID   `json:"id"`
	UserID           uuid.UUID   `json:"user_id"`
	RefreshTokenHash []byte      `json:"refresh_token_hash"`
	FamilyID         uuid.UUID   `json:"family_id"`
	DeviceName       pgtype.Text `json:"device_name"`
	Platform         string      `json:"platform"`
	Ip               *netip.Addr `json:"ip"`
	ExpiresAt        time.Time   `json:"expires_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.FamilyID,
		arg.DeviceName,
		arg.Platform,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.FamilyID,
		&i.DeviceName,
		&i.Platform,
		&i.Ip,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLiveSessionsByFamilyID = `-- name: ListLiveSessionsByFamilyID :many
SELECT id, user_id, refresh_token_hash, family_id, device_name, platform, ip, last_used_at, expires_at, revoked_at, created_at, updated_at FROM sessions WHERE family_id = $1 AND revoked_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListLiveSessionsByFamilyID(ctx context.Context, familyID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listLiveSessionsByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.FamilyID,
			&i.DeviceName,
			&i.Platform,
			&i.Ip,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now(), updated_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :exec
UPDATE sessions SET revoked_at = now(), updated_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionFamily, familyID)
	return err
}

const touchSessionLastUsed = `-- name: TouchSessionLastUsed :exec
UPDATE sessions SET last_used_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) TouchSessionLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSessionLastUsed, id)
	return err
}
