// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUnitByID = `-- name: GetUnitByID :one
SELECT id, community_id, block, floor, door, type, participation_coefficient, cadastral_ref, deleted_at, created_at, updated_at FROM units WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUnitByID(ctx context.Context, id uuid.UUID) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByID, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Block,
		&i.Floor,
		&i.Door,
		&i.Type,
		&i.ParticipationCoefficient,
		&i.CadastralRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitCommunityID = `-- name: GetUnitCommunityID :one
SELECT community_id FROM units WHERE id = $1 AND deleted_at IS NULL
`

// Unit resolver (design D-4): a {unitId} route resolves community
// membership via the unit's own community_id, never a caller-supplied
// value.
func (q *Queries) GetUnitCommunityID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUnitCommunityID, id)
	var community_id uuid.UUID
	err := row.Scan(&community_id)
	return community_id, err
}

const insertUnit = `-- name: InsertUnit :one
INSERT INTO units (id, community_id, block, floor, door, type, participation_coefficient, cadastral_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, community_id, block, floor, door, type, participation_coefficient, cadastral_ref, deleted_at, created_at, updated_at
`

type InsertUnitParams struct {
	ID                       uuid.UUID      `json:"id"`
	CommunityID              uuid.UUID      `json:"community_id"`
	Block                    pgtype.Text    `json:"block"`
	Floor                    pgtype.Text    `json:"floor"`
	Door                     pgtype.Text    `json:"door"`
	Type                     string         `json:"type"`
	ParticipationCoefficient pgtype.Numeric `json:"participation_coefficient"`
	CadastralRef             pgtype.Text    `json:"cadastral_ref"`
}

// units: tenant column community_id (design D-5).
func (q *Queries) InsertUnit(ctx context.Context, arg InsertUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, insertUnit,
		arg.ID,
		arg.CommunityID,
		arg.Block,
		arg.Floor,
		arg.Door,
		arg.Type,
		arg.ParticipationCoefficient,
		arg.CadastralRef,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.Block,
		&i.Floor,
		&i.Door,
		&i.Type,
		&i.ParticipationCoefficient,
		&i.CadastralRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnitsByCommunityID = `-- name: ListUnitsByCommunityID :many
SELECT id, community_id, block, floor, door, type, participation_coefficient, cadastral_ref, deleted_at, created_at, updated_at FROM units WHERE community_id = $1 AND deleted_at IS NULL ORDER BY block, floor, door
`

func (q *Queries) ListUnitsByCommunityID(ctx context.Context, communityID uuid.UUID) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnitsByCommunityID, communityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.Block,
			&i.Floor,
			&i.Door,
			&i.Type,
			&i.ParticipationCoefficient,
			&i.CadastralRef,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
