// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_mfa.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmUserMFAEnrollment = `-- name: ConfirmUserMFAEnrollment :exec
UPDATE user_mfa SET enabled_at = now(), updated_at = now() WHERE user_id = $1
`

func (q *Queries) ConfirmUserMFAEnrollment(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmUserMFAEnrollment, userID)
	return err
}

const consumeUserMFARecoveryCode = `-- name: ConsumeUserMFARecoveryCode :execrows
UPDATE user_mfa SET recovery_codes_hashed = array_remove(recovery_codes_hashed, $2), updated_at = now()
WHERE user_id = $1 AND $2 = ANY(recovery_codes_hashed)
`

type ConsumeUserMFARecoveryCodeParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	ArrayRemove interface{} `json:"array_remove"`
}

func (q *Queries) ConsumeUserMFARecoveryCode(ctx context.Context, arg ConsumeUserMFARecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeUserMFARecoveryCode, arg.UserID, arg.ArrayRemove)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserMFA = `-- name: GetUserMFA :one
SELECT user_id, totp_secret_encrypted, enabled_at, last_totp_step, recovery_codes_hashed, created_at, updated_at FROM user_mfa WHERE user_id = $1
`

func (q *Queries) GetUserMFA(ctx context.Context, userID uuid.UUID) (UserMfa, error) {
	row := q.db.QueryRow(ctx, getUserMFA, userID)
	var i UserMfa
	err := row.Scan(
		&i.UserID,
		&i.TotpSecretEncrypted,
		&i.EnabledAt,
		&i.LastTotpStep,
		&i.RecoveryCodesHashed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserMFARecoveryCodes = `-- name: SetUserMFARecoveryCodes :exec
UPDATE user_mfa SET recovery_codes_hashed = $2, updated_at = now() WHERE user_id = $1
`

type SetUserMFARecoveryCodesParams struct {
	UserID              uuid.UUID `json:"user_id"`
	RecoveryCodesHashed []string  `json:"recovery_codes_hashed"`
}

func (q *Queries) SetUserMFARecoveryCodes(ctx context.Context, arg SetUserMFARecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, setUserMFARecoveryCodes, arg.UserID, arg.RecoveryCodesHashed)
	return err
}

const updateUserMFALastTOTPStep = `-- name: UpdateUserMFALastTOTPStep :execrows
UPDATE user_mfa SET last_totp_step = $2, updated_at = now()
WHERE user_id = $1 AND (last_totp_step IS NULL OR last_totp_step < $2)
`

type UpdateUserMFALastTOTPStepParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	LastTotpStep pgtype.Int8 `json:"last_totp_step"`
}

func (q *Queries) UpdateUserMFALastTOTPStep(ctx context.Context, arg UpdateUserMFALastTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserMFALastTOTPStep, arg.UserID, arg.LastTotpStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertUserMFA = `-- name: UpsertUserMFA :one
INSERT INTO user_mfa (user_id, totp_secret_encrypted)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET totp_secret_encrypted = EXCLUDED.totp_secret_encrypted, updated_at = now()
RETURNING user_id, totp_secret_encrypted, enabled_at, last_totp_step, recovery_codes_hashed, created_at, updated_at
`

type UpsertUserMFAParams struct {
	UserID              uuid.UUID `json:"user_id"`
	TotpSecretEncrypted []byte    `json:"totp_secret_encrypted"`
}

func (q *Queries) UpsertUserMFA(ctx context.Context, arg UpsertUserMFAParams) (UserMfa, error) {
	row := q.db.QueryRow(ctx, upsertUserMFA, arg.UserID, arg.TotpSecretEncrypted)
	var i UserMfa
	err := row.Scan(
		&i.UserID,
		&i.TotpSecretEncrypted,
		&i.EnabledAt,
		&i.LastTotpStep,
		&i.RecoveryCodesHashed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
