// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const ensureSuperadmin = `-- name: EnsureSuperadmin :exec
UPDATE users SET is_superadmin = true, updated_at = now() WHERE id = $1 AND is_superadmin = false
`

// platform-bootstrap: Idempotent Superadmin Bootstrap -- a second
// bootstrap-superadmin run against an existing, non-superadmin user
// (e.g. one first created by seed) promotes it, but NEVER touches its
// password_hash.
func (q *Queries) EnsureSuperadmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureSuperadmin, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, phone, phone_verified_at, locale, avatar_key, id_document_encrypted, notification_prefs, is_superadmin, last_login_at, deleted_at, created_at, updated_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.Locale,
		&i.AvatarKey,
		&i.IDDocumentEncrypted,
		&i.NotificationPrefs,
		&i.IsSuperadmin,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, phone, phone_verified_at, locale, avatar_key, id_document_encrypted, notification_prefs, is_superadmin, last_login_at, deleted_at, created_at, updated_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.Locale,
		&i.AvatarKey,
		&i.IDDocumentEncrypted,
		&i.NotificationPrefs,
		&i.IsSuperadmin,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, email, password_hash, name, phone, locale, is_superadmin)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, password_hash, name, phone, phone_verified_at, locale, avatar_key, id_document_encrypted, notification_prefs, is_superadmin, last_login_at, deleted_at, created_at, updated_at
`

type InsertUserParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	Phone        pgtype.Text `json:"phone"`
	Locale       string      `json:"locale"`
	IsSuperadmin bool        `json:"is_superadmin"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Phone,
		arg.Locale,
		arg.IsSuperadmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.PhoneVerifiedAt,
		&i.Locale,
		&i.AvatarKey,
		&i.IDDocumentEncrypted,
		&i.NotificationPrefs,
		&i.IsSuperadmin,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserIgnoreConflict = `-- name: InsertUserIgnoreConflict :execrows
INSERT INTO users (id, email, password_hash, name, phone, locale, is_superadmin)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (email) DO NOTHING
`

type InsertUserIgnoreConflictParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	Phone        pgtype.Text `json:"phone"`
	Locale       string      `json:"locale"`
	IsSuperadmin bool        `json:"is_superadmin"`
}

// platform-bootstrap: Idempotent Superadmin Bootstrap / seed Refuses To
// Run Outside Non-Production -- both bootstrap-superadmin and seed need
// an idempotent insert that never duplicates and never errors on a
// second run. Zero affected rows means the email already existed; the
// caller is expected to load the existing row (GetUserByEmail) and, for
// bootstrap-superadmin only, ensure is_superadmin via EnsureSuperadmin.
func (q *Queries) InsertUserIgnoreConflict(ctx context.Context, arg InsertUserIgnoreConflictParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUserIgnoreConflict,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Phone,
		arg.Locale,
		arg.IsSuperadmin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = $2, updated_at = now() WHERE id = $1
`

type UpdateUserLastLoginParams struct {
	ID          uuid.UUID          `json:"id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.ID, arg.LastLoginAt)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
